### ISSUE TITLE
Replace `parameter_types` with `ConstU32` &c.

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#10383]
Most simple `parameter_types` declarations can be replaced with the new `ConstU32`, `ConstU64`, `ConstU128` and `ConstBool`, reducing some unneeded verbosity.

**Comment by dharjeezy** [comment]
Picking this up @gavofyork

**Comment by dharjeezy** [comment]
@gavofyork i see in your PR here https://github.com/paritytech/substrate/pull/10382 that you have defined the implementation for ConstU64, ConstU128 and ConstBool, as only  ConstU32 is available in master.

Should i wait for your PR to get merged before solving this issue?

**Comment by gavofyork** [comment]
You could just start on a branch which brings in that change.

**Comment by dharjeezy** [comment]
When you say start on a branch, Are you saying i should start off on my own branch which I already started(changing parameter types for ConstU32)?

More so, are you saying i should implement the `ConstU64, ConstU128 and ConstBool` on my own branch?

@gavofyork

**Comment by gavofyork** [comment]
> More so, are you saying i should implement the ConstU64, ConstU128 and ConstBool on my own branch?

YEs, you could copy that code in if it's going to be useful (and it probably is).

**Comment by dharjeezy** [comment]
I have started the implementation as opened in the PR
@gavofyork

**Comment by KiChjang** [comment]
Fixed by #10402.

**Comment by thiolliere** [comment]
some place could still be replaced https://github.com/paritytech/substrate/pull/10402#issuecomment-995374677

**Comment by bizzyvinci** [comment]
This issue is still open?

**Comment by bkchr** [comment]
@bizzyvinci have you checked the mentioned code?

**Comment by bizzyvinci** [comment]
Yes. 
[This] seems resolved already but the issue remains open
